### ISSUE TITLE
Activity is destroyed when app goes to background and reopened by tapping on app icon

### ISSUE THREAD

**Issue by 0xsilver-bullet** [moshfiqrony/react-native-android-native-mergerd-boilerplate#24]
When you open a new activity and then move the app to background,
onPause() and onStop() are called normally on the new native activity.
but when you open the app again by tapping on it's icon,
suddenly onDestory() is called on the new activity so it gets destroyed and the MainActivity (actvitiy that hosts RN) opens again

**Comment by moshfiqrony** [comment]
Thanks for your issue. Unfortunately currently I am not maintaining this repo and won't be able to give you a quick update on this.
